ALTER TABLE open_ports
    ADD COLUMN IF NOT EXISTS product TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS version TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS cpe TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS cves TEXT[] NOT NULL DEFAULT '{}';
